#pragma once

#define DEFAULT_PORT "/dev/ttyTHS1"

#define ENCODER_MIN 0
#define ENCODER_MAX 9000
#define ENCODER_LOW_WRAP_FACTOR 0.3
#define ENCODER_HIGH_WRAP_FACTOR 0.7

#define TICKS_PER_ROTATION 90
